### ISSUE TITLE
Update to Julia 0.6

### ISSUE THREAD

**Issue by willingc** [choldgraf/demo-julia#1]
@choldgraf Very cool! Since you did this demo, Julia released 0.6. Let's update to that version :-)

**Comment by choldgraf** [comment]
that's a good idea!!

**Comment by choldgraf** [comment]
see https://github.com/jupyter/repo2docker/pull/30

**Comment by Krastanov** [comment]
Maybe a version bump to the stable Julia 1.0 release would be appropriate now?
