### ISSUE TITLE
Move to Binder-Examples Org?

### ISSUE THREAD

**Issue by jzf2101** [choldgraf/demo-julia#2]
This is supposed to be a monolingual julia example, which binder-examples does not yet have. Do we want this to get adopted by the Jupyter org?

**Comment by choldgraf** [comment]
oops! I must have forgotten about this way back when - we should update the README so that it follows the pattern of the other binder-examples projects

**Comment by jzf2101** [comment]
I want to know because I'm citing this in a paper and want to know if I should give this to the Project Jupyter org

**Comment by choldgraf** [comment]
yep we should definitely do that! I'll transfer it over now
