### ISSUE TITLE
Make the link on https://jupyter.org/try point here

### ISSUE THREAD

**Issue by davidanthoff** [choldgraf/demo-julia#7]
I think this would make a much better julia example than the one that is currently linked to from https://jupyter.org/try (which uses a very outdated version of Julia).

**Comment by choldgraf** [comment]
that seems reasonable to me! I think that'd be a PR in the website repository (https://github.com/jupyter/jupyter.github.io)...happy to give it a review though I'm not sure if I can merge there or not

**Comment by davidanthoff** [comment]
Thanks, I just opened a PR: https://github.com/jupyter/jupyter.github.io/pull/346

**Comment by choldgraf** [comment]
done!
